#!/bin/bash
#create dir and file

if [ ! $# -eq 2 ]
then
echo "Usage: ./mkdirplus [folder] [filename]"
exit 1
fi

if [ -d $1 ]
then
echo $1" already exists as a directory"
exit 2
fi

mkdir $1
touch $1/$2.txt
echo "Matthew doesn't like pizza" > $1/$2.txt
echo "Folder and file successfully added"
exit 0
